// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VLI.SIOP.Operacao.Dados;

namespace easyharbour.Dados.Migrations
{
    [DbContext(typeof(AplicacaoContexto))]
    [Migration("20201120171943_addMare")]
    partial class addMare
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("easyharbour.Model.TabuaMare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Altura");

                    b.Property<DateTime>("Data");

                    b.HasKey("Id");

                    b.ToTable("TabuaMares");
                });

            modelBuilder.Entity("easyharbour.Models.Navio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Descritivo");

                    b.HasKey("Id");

                    b.ToTable("Navios");
                });
#pragma warning restore 612, 618
        }
    }
}
