// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VLI.SIOP.Operacao.Dados;

namespace easyharbour.Dados.Migrations
{
    [DbContext(typeof(AplicacaoContexto))]
    partial class AplicacaoContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("easyharbour.Model.Atracacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AtracacaoEfetiva");

                    b.Property<DateTime?>("Autorizacao");

                    b.Property<DateTime>("AvisoChegada");

                    b.Property<DateTime?>("Desatracacao");

                    b.Property<bool>("EmOperacao");

                    b.Property<bool>("Fundiado");

                    b.Property<string>("Navio");

                    b.Property<string>("Operador");

                    b.Property<DateTime?>("PrevisaoAtracacao");

                    b.Property<int>("Viagem");

                    b.HasKey("Id");

                    b.ToTable("Atracacoes");
                });

            modelBuilder.Entity("easyharbour.Model.TabuaMare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Altura");

                    b.Property<DateTime>("Data");

                    b.HasKey("Id");

                    b.ToTable("TabuaMares");
                });

            modelBuilder.Entity("easyharbour.Models.Navio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Descritivo");

                    b.HasKey("Id");

                    b.ToTable("Navios");
                });
#pragma warning restore 612, 618
        }
    }
}
